import type { RepairEvent } from '../types';

export const REPAIR_EVENTS: RepairEvent[] = [
  { id: 'corolla-engine', modelIds: ['corolla-e120'], category: 'engine', name: 'Серьёзный ремонт двигателя', probability5y: 0.15, repairCost: 90000, coefficient: 1.25, maxCost: 150000, monthStart: 24, monthEnd: 60 },
  { id: 'corolla-transmission', modelIds: ['corolla-e120'], category: 'transmission', name: 'Ремонт АКПП', probability5y: 0.10, repairCost: 65000, coefficient: 1.25, maxCost: 120000, monthStart: 12, monthEnd: 60 },
  { id: 'corolla-suspension', modelIds: ['corolla-e120'], category: 'suspension', name: 'Комплексный ремонт подвески', probability5y: 0.35, repairCost: 30000, coefficient: 1.15, maxCost: 50000, monthStart: 12, monthEnd: 60 },
  { id: 'corolla-ac', modelIds: ['corolla-e120'], category: 'ac', name: 'Ремонт кондиционера', probability5y: 0.20, repairCost: 45000, coefficient: 1.20, maxCost: 70000, monthStart: 12, monthEnd: 60 },
  { id: 'corolla-electrics', modelIds: ['corolla-e120'], category: 'electrics', name: 'Сложная неисправность электрики', probability5y: 0.25, repairCost: 25000, coefficient: 1.25, maxCost: 40000, monthStart: 12, monthEnd: 60 },
  { id: 'cerato-engine', modelIds: ['cerato-ld'], category: 'engine', name: 'Серьёзный ремонт двигателя', probability5y: 0.18, repairCost: 90000, coefficient: 1.25, maxCost: 150000, monthStart: 24, monthEnd: 60 },
  { id: 'cerato-transmission', modelIds: ['cerato-ld'], category: 'transmission', name: 'Ремонт АКПП', probability5y: 0.12, repairCost: 65000, coefficient: 1.25, maxCost: 125000, monthStart: 12, monthEnd: 60 },
  { id: 'cerato-suspension', modelIds: ['cerato-ld'], category: 'suspension', name: 'Комплексный ремонт подвески', probability5y: 0.38, repairCost: 30000, coefficient: 1.15, maxCost: 50000, monthStart: 12, monthEnd: 60 },
  { id: 'cerato-ac', modelIds: ['cerato-ld'], category: 'ac', name: 'Ремонт кондиционера', probability5y: 0.24, repairCost: 45000, coefficient: 1.20, maxCost: 70000, monthStart: 12, monthEnd: 60 },
  { id: 'cerato-electrics', modelIds: ['cerato-ld'], category: 'electrics', name: 'Сложная неисправность электрики', probability5y: 0.28, repairCost: 25000, coefficient: 1.25, maxCost: 40000, monthStart: 12, monthEnd: 60 },
  { id: 'lacetti-engine', modelIds: ['lacetti-hatch'], category: 'engine', name: 'Серьёзный ремонт двигателя', probability5y: 0.20, repairCost: 90000, coefficient: 1.25, maxCost: 150000, monthStart: 24, monthEnd: 60 },
  { id: 'lacetti-transmission', modelIds: ['lacetti-hatch'], category: 'transmission', name: 'Ремонт АКПП', probability5y: 0.14, repairCost: 65000, coefficient: 1.25, maxCost: 125000, monthStart: 12, monthEnd: 60 },
  { id: 'lacetti-suspension', modelIds: ['lacetti-hatch'], category: 'suspension', name: 'Комплексный ремонт подвески', probability5y: 0.42, repairCost: 30000, coefficient: 1.15, maxCost: 50000, monthStart: 12, monthEnd: 60 },
  { id: 'lacetti-ac', modelIds: ['lacetti-hatch'], category: 'ac', name: 'Ремонт кондиционера', probability5y: 0.26, repairCost: 45000, coefficient: 1.20, maxCost: 70000, monthStart: 12, monthEnd: 60 },
  { id: 'lacetti-electrics', modelIds: ['lacetti-hatch'], category: 'electrics', name: 'Сложная неисправность электрики', probability5y: 0.30, repairCost: 25000, coefficient: 1.25, maxCost: 40000, monthStart: 12, monthEnd: 60 },
  { id: 'corolla-timing-chain', modelIds: ['corolla-e120'], category: 'maintenance', name: 'Проверка/замена цепи ГРМ и натяжителя', probability5y: 0.25, repairCost: 30000, coefficient: 1.15, maxCost: 50000, monthStart: 24, monthEnd: 60 },
  { id: 'timing-belt', modelIds: ['cerato-ld', 'lacetti-hatch'], category: 'maintenance', name: 'Замена ремня ГРМ и роликов', probability5y: 0.65, repairCost: 30000, coefficient: 1.10, maxCost: 45000, monthStart: 1, monthEnd: 6 },
  { id: 'brakes-full', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'brakes', name: 'Комплект тормозов', probability5y: 0.55, repairCost: 30000, coefficient: 1.15, maxCost: 45000, monthStart: 1, monthEnd: 24 },
  { id: 'battery', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'electrics', name: 'Замена аккумулятора', probability5y: 0.45, repairCost: 12000, coefficient: 1.10, maxCost: 18000, monthStart: 1, monthEnd: 36 },
  { id: 'fluids-refresh', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'maintenance', name: 'Замена жидкостей и свечей', probability5y: 0.70, repairCost: 14000, coefficient: 1.10, maxCost: 22000, monthStart: 1, monthEnd: 12 },
  { id: 'wheel-bearing', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'suspension', name: 'Замена ступичного подшипника', probability5y: 0.30, repairCost: 18000, coefficient: 1.15, maxCost: 30000, monthStart: 12, monthEnd: 60 },
  { id: 'suspension-bushings', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'suspension', name: 'Сайлентблоки и втулки', probability5y: 0.45, repairCost: 22000, coefficient: 1.15, maxCost: 35000, monthStart: 12, monthEnd: 48 },
  { id: 'starter-generator', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'electrics', name: 'Генератор или стартер', probability5y: 0.22, repairCost: 35000, coefficient: 1.25, maxCost: 60000, monthStart: 18, monthEnd: 60 },
  { id: 'exhaust-repair', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'exhaust', name: 'Ремонт выхлопной системы', probability5y: 0.35, repairCost: 18000, coefficient: 1.20, maxCost: 30000, monthStart: 12, monthEnd: 60 },
  { id: 'rust-prevention', modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'], category: 'body', name: 'Повторная обработка очагов коррозии', probability5y: 0.28, repairCost: 25000, coefficient: 1.20, maxCost: 45000, monthStart: 18, monthEnd: 60 },
];
