import type { AppConfig, CategoryId, ModelId } from './types';
import { DEFAULT_INSPECTION_TEMPLATES } from './inspectionTemplates';

export const MODEL_LABELS: Record<ModelId, string> = {
  'corolla-e120': 'Toyota Corolla E120 1.6 AT',
  'cerato-ld': 'Kia Cerato LD 1.6 AT',
  'lacetti-hatch': 'Chevrolet Lacetti Hatch 1.6 AT',
};

export const CATEGORIES: Array<{ id: CategoryId; label: string; subcategories: string[] }> = [
  { id: 'maintenance', label: 'ТО', subcategories: ['Масла и фильтры', 'Жидкости', 'Регламентные работы'] },
  {
    id: 'engine',
    label: 'Двигатель',
    subcategories: ['Мелкий ремонт', 'Средний ремонт', 'Крупный ремонт', 'Диагностика'],
  },
  { id: 'transmission', label: 'АКПП', subcategories: ['Обслуживание', 'Ремонт', 'Диагностика'] },
  { id: 'suspension', label: 'Подвеска', subcategories: ['Передняя', 'Задняя', 'Амортизаторы', 'Ступицы'] },
  { id: 'brakes', label: 'Тормоза', subcategories: ['Диски и колодки', 'Суппорты', 'Трубки и шланги'] },
  { id: 'steering', label: 'Рулевое', subcategories: ['Рейка', 'Тяги и наконечники', 'ГУР'] },
  { id: 'cooling', label: 'Охлаждение', subcategories: ['Радиатор', 'Помпа и термостат', 'Патрубки'] },
  { id: 'ac', label: 'Кондиционер', subcategories: ['Диагностика', 'Компрессор', 'Радиатор и магистрали'] },
  { id: 'electrics', label: 'Электрика', subcategories: ['Диагностика', 'Проводка', 'Генератор и стартер', 'Комфорт'] },
  {
    id: 'body',
    label: 'Кузов',
    subcategories: ['Локальный ремонт', 'Несколько элементов', 'Полный окрас', 'Сварка', 'Геометрия'],
  },
  { id: 'tires', label: 'Резина', subcategories: ['Летняя', 'Зимняя', 'Диски'] },
  { id: 'interior', label: 'Салон', subcategories: ['Обивка', 'Пластик', 'Химчистка'] },
  { id: 'exhaust', label: 'Выхлоп', subcategories: ['Глушитель', 'Катализатор', 'Крепления'] },
  { id: 'other', label: 'Прочее', subcategories: ['Не классифицировано'] },
];

const years = (value: number) => Array.from({ length: 5 }, () => value);

export const DEFAULT_CONFIG: AppConfig = {
  id: 'current',
  version: 'seed-2026-08-27',
  fund: 500000,
  maxAskingPrice: 465000,
  targetPurchasePrice: 400000,
  greenReserveRatio: 0.2,
  yellowReserveRatio: 0.1,
  majorRepairThreshold: 25000,
  criticalRepairThreshold: 120000,
  majorRepairsPerYearLimit: 4,
  minMonthsBetweenMajorRepairs: 3,
  // 4000 сценариев дают вероятность с точностью около ±0,8 п.п. при 95% доверии.
  // Этого достаточно для шкалы рейтинга, а расчёт при этом идёт в пять раз быстрее:
  // он выполняется синхронно при каждом изменении осмотра, в том числе на телефоне.
  simulationScenarios: 4000,
  simulationSeed: 20260827,
  ratingWeights: {
    budget: 20,
    ownership: 20,
    annualRisk: 10,
    frequency: 10,
    maxRepair: 10,
    engine: 10,
    transmission: 10,
    predictability: 5,
    service: 5,
    vehicleInfo: 5,
  },
  scenario: {
    years: 5,
    annualKm: 12000,
    fuelPrice: 71,
    insuranceByYear: [40000, 40000, 40000, 40000, 40000],
    serviceByYear: years(28000),
    fluidsByYear: years(8000),
    consumablesByYear: years(10000),
    tiresByYear: years(14000),
    washingByYear: years(12000),
    finesByYear: years(3000),
    annualLimit: 300000,
  },
  models: [
    {
      id: 'corolla-e120',
      isBuiltIn: true,
      make: 'Toyota',
      model: 'Corolla',
      generation: 'E120',
      engine: '1.6',
      transmission: 'AT',
      engineVariants: [
        {
          id: '3zz-fe',
          label: '3ZZ-FE 1.6 VVT-i — цепь ГРМ',
          code: '3ZZ-FE',
          timingDrive: 'CHAIN',
          note: 'Основная европейская 1.6-литровая версия E120.',
        },
        {
          id: 'unknown',
          label: 'Код двигателя не установлен',
          code: '',
          timingDrive: 'UNKNOWN',
          note: 'Уточнить по VIN и маркировке двигателя.',
        },
      ],
      consumptionLPer100Km: 8.5,
      taxAnnual: 2400,
    },
    {
      id: 'cerato-ld',
      isBuiltIn: true,
      make: 'Kia',
      model: 'Cerato',
      generation: 'LD',
      engine: '1.6',
      transmission: 'AT',
      engineVariants: [
        {
          id: 'g4ed',
          label: 'G4ED 1.6 — ремень ГРМ',
          code: 'G4ED',
          timingDrive: 'BELT',
          note: 'Для этой версии важно подтвердить дату последней замены комплекта ГРМ.',
        },
        {
          id: 'unknown',
          label: 'Код двигателя не установлен',
          code: '',
          timingDrive: 'UNKNOWN',
          note: 'Уточнить по VIN и маркировке двигателя.',
        },
      ],
      consumptionLPer100Km: 9.0,
      taxAnnual: 2400,
    },
    {
      id: 'lacetti-hatch',
      isBuiltIn: true,
      make: 'Chevrolet',
      model: 'Lacetti Hatch',
      generation: 'J200',
      engine: '1.6',
      transmission: 'AT',
      engineVariants: [
        {
          id: 'f16d3',
          label: 'F16D3 1.6 16V — ремень ГРМ',
          code: 'F16D3',
          timingDrive: 'BELT',
          note: 'Проверить комплект ГРМ, ролики и помпу по истории обслуживания.',
        },
        {
          id: 'unknown',
          label: 'Код двигателя не установлен',
          code: '',
          timingDrive: 'UNKNOWN',
          note: 'Уточнить по VIN и маркировке двигателя.',
        },
      ],
      consumptionLPer100Km: 9.5,
      taxAnnual: 2400,
    },
  ],
  coefficients: [
    { id: 'maintenance', category: 'maintenance', label: 'ТО', coefficient: 1.1 },
    { id: 'engine-minor', category: 'engine', label: 'Двигатель — мелкий ремонт', coefficient: 1.2 },
    { id: 'engine-medium', category: 'engine', label: 'Двигатель — средний ремонт', coefficient: 1.2 },
    { id: 'engine-major', category: 'engine', label: 'Двигатель — крупный ремонт', coefficient: 1.25 },
    { id: 'engine-diagnostic', category: 'engine', label: 'Двигатель — диагностика', coefficient: 1.2 },
    { id: 'transmission-service', category: 'transmission', label: 'АКПП — обслуживание', coefficient: 1.1 },
    { id: 'transmission-repair', category: 'transmission', label: 'АКПП — ремонт', coefficient: 1.25 },
    { id: 'transmission-diagnostic', category: 'transmission', label: 'АКПП — диагностика', coefficient: 1.1 },
    { id: 'suspension', category: 'suspension', label: 'Подвеска', coefficient: 1.15 },
    { id: 'brakes', category: 'brakes', label: 'Тормоза', coefficient: 1.15 },
    { id: 'steering', category: 'steering', label: 'Рулевое', coefficient: 1.2 },
    { id: 'cooling', category: 'cooling', label: 'Охлаждение', coefficient: 1.2 },
    { id: 'ac', category: 'ac', label: 'Кондиционер', coefficient: 1.2 },
    { id: 'electrics', category: 'electrics', label: 'Электрика', coefficient: 1.25 },
    { id: 'body-local', category: 'body', label: 'Кузов — локальный ремонт', coefficient: 1.15 },
    { id: 'body-multiple', category: 'body', label: 'Кузов — несколько элементов', coefficient: 1.2 },
    { id: 'body-paint', category: 'body', label: 'Кузов — полный окрас', coefficient: 1.2 },
    { id: 'body-welding', category: 'body', label: 'Кузов — сварка', coefficient: 1.25 },
    { id: 'body-geometry', category: 'body', label: 'Кузов — геометрия', coefficient: 1.25 },
    { id: 'tires', category: 'tires', label: 'Резина', coefficient: 1.1 },
    { id: 'interior', category: 'interior', label: 'Салон', coefficient: 1.1 },
    { id: 'exhaust', category: 'exhaust', label: 'Выхлоп', coefficient: 1.2 },
    { id: 'other', category: 'other', label: 'Прочее', coefficient: 1.2 },
  ],
  repairEvents: [
    {
      id: 'corolla-engine',
      modelIds: ['corolla-e120'],
      category: 'engine',
      name: 'Серьёзный ремонт двигателя',
      probability5y: 0.15,
      repairCost: 90000,
      coefficient: 1.25,
      maxCost: 150000,
      monthStart: 24,
      monthEnd: 60,
    },
    {
      id: 'corolla-transmission',
      modelIds: ['corolla-e120'],
      category: 'transmission',
      name: 'Ремонт АКПП',
      probability5y: 0.1,
      repairCost: 65000,
      coefficient: 1.25,
      maxCost: 120000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'corolla-suspension',
      modelIds: ['corolla-e120'],
      category: 'suspension',
      name: 'Комплексный ремонт подвески',
      probability5y: 0.35,
      repairCost: 30000,
      coefficient: 1.15,
      maxCost: 50000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'corolla-ac',
      modelIds: ['corolla-e120'],
      category: 'ac',
      name: 'Ремонт кондиционера',
      probability5y: 0.2,
      repairCost: 45000,
      coefficient: 1.2,
      maxCost: 70000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'corolla-electrics',
      modelIds: ['corolla-e120'],
      category: 'electrics',
      name: 'Сложная неисправность электрики',
      probability5y: 0.25,
      repairCost: 25000,
      coefficient: 1.25,
      maxCost: 40000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'cerato-engine',
      modelIds: ['cerato-ld'],
      category: 'engine',
      name: 'Серьёзный ремонт двигателя',
      probability5y: 0.18,
      repairCost: 90000,
      coefficient: 1.25,
      maxCost: 150000,
      monthStart: 24,
      monthEnd: 60,
    },
    {
      id: 'cerato-transmission',
      modelIds: ['cerato-ld'],
      category: 'transmission',
      name: 'Ремонт АКПП',
      probability5y: 0.12,
      repairCost: 65000,
      coefficient: 1.25,
      maxCost: 125000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'cerato-suspension',
      modelIds: ['cerato-ld'],
      category: 'suspension',
      name: 'Комплексный ремонт подвески',
      probability5y: 0.38,
      repairCost: 30000,
      coefficient: 1.15,
      maxCost: 50000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'cerato-ac',
      modelIds: ['cerato-ld'],
      category: 'ac',
      name: 'Ремонт кондиционера',
      probability5y: 0.24,
      repairCost: 45000,
      coefficient: 1.2,
      maxCost: 70000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'cerato-electrics',
      modelIds: ['cerato-ld'],
      category: 'electrics',
      name: 'Сложная неисправность электрики',
      probability5y: 0.28,
      repairCost: 25000,
      coefficient: 1.25,
      maxCost: 40000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'lacetti-engine',
      modelIds: ['lacetti-hatch'],
      category: 'engine',
      name: 'Серьёзный ремонт двигателя',
      probability5y: 0.2,
      repairCost: 90000,
      coefficient: 1.25,
      maxCost: 150000,
      monthStart: 24,
      monthEnd: 60,
    },
    {
      id: 'lacetti-transmission',
      modelIds: ['lacetti-hatch'],
      category: 'transmission',
      name: 'Ремонт АКПП',
      probability5y: 0.14,
      repairCost: 65000,
      coefficient: 1.25,
      maxCost: 125000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'lacetti-suspension',
      modelIds: ['lacetti-hatch'],
      category: 'suspension',
      name: 'Комплексный ремонт подвески',
      probability5y: 0.42,
      repairCost: 30000,
      coefficient: 1.15,
      maxCost: 50000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'lacetti-ac',
      modelIds: ['lacetti-hatch'],
      category: 'ac',
      name: 'Ремонт кондиционера',
      probability5y: 0.26,
      repairCost: 45000,
      coefficient: 1.2,
      maxCost: 70000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'lacetti-electrics',
      modelIds: ['lacetti-hatch'],
      category: 'electrics',
      name: 'Сложная неисправность электрики',
      probability5y: 0.3,
      repairCost: 25000,
      coefficient: 1.25,
      maxCost: 40000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'corolla-timing-chain',
      modelIds: ['corolla-e120'],
      category: 'maintenance',
      name: 'Проверка/замена цепи ГРМ и натяжителя',
      probability5y: 0.25,
      repairCost: 30000,
      coefficient: 1.15,
      maxCost: 50000,
      monthStart: 24,
      monthEnd: 60,
    },
    {
      id: 'timing-belt',
      modelIds: ['cerato-ld', 'lacetti-hatch'],
      category: 'maintenance',
      name: 'Замена ремня ГРМ и роликов',
      probability5y: 0.65,
      repairCost: 30000,
      coefficient: 1.1,
      maxCost: 45000,
      monthStart: 1,
      monthEnd: 6,
    },
    {
      id: 'brakes-full',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'brakes',
      name: 'Комплект тормозов',
      probability5y: 0.55,
      repairCost: 30000,
      coefficient: 1.15,
      maxCost: 45000,
      monthStart: 1,
      monthEnd: 24,
    },
    {
      id: 'battery',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'electrics',
      name: 'Замена аккумулятора',
      probability5y: 0.45,
      repairCost: 12000,
      coefficient: 1.1,
      maxCost: 18000,
      monthStart: 1,
      monthEnd: 36,
    },
    {
      id: 'fluids-refresh',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'maintenance',
      name: 'Замена жидкостей и свечей',
      probability5y: 0.7,
      repairCost: 14000,
      coefficient: 1.1,
      maxCost: 22000,
      monthStart: 1,
      monthEnd: 12,
    },
    {
      id: 'wheel-bearing',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'suspension',
      name: 'Замена ступичного подшипника',
      probability5y: 0.3,
      repairCost: 18000,
      coefficient: 1.15,
      maxCost: 30000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'suspension-bushings',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'suspension',
      name: 'Сайлентблоки и втулки',
      probability5y: 0.45,
      repairCost: 22000,
      coefficient: 1.15,
      maxCost: 35000,
      monthStart: 12,
      monthEnd: 48,
    },
    {
      id: 'starter-generator',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'electrics',
      name: 'Генератор или стартер',
      probability5y: 0.22,
      repairCost: 35000,
      coefficient: 1.25,
      maxCost: 60000,
      monthStart: 18,
      monthEnd: 60,
    },
    {
      id: 'exhaust-repair',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'exhaust',
      name: 'Ремонт выхлопной системы',
      probability5y: 0.35,
      repairCost: 18000,
      coefficient: 1.2,
      maxCost: 30000,
      monthStart: 12,
      monthEnd: 60,
    },
    {
      id: 'rust-prevention',
      modelIds: ['corolla-e120', 'cerato-ld', 'lacetti-hatch'],
      category: 'body',
      name: 'Повторная обработка очагов коррозии',
      probability5y: 0.28,
      repairCost: 25000,
      coefficient: 1.2,
      maxCost: 45000,
      monthStart: 18,
      monthEnd: 60,
    },
  ],
  templates: DEFAULT_INSPECTION_TEMPLATES,
};

export function cloneConfig(config: AppConfig): AppConfig {
  return JSON.parse(JSON.stringify(config)) as AppConfig;
}

export function modelLabel(modelId: ModelId): string {
  return MODEL_LABELS[modelId] ?? modelId;
}
